name: Build, Test and Deploy a .NET Core WebApi to Azure App Service

env: # Change these settings if you like
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: "./ProjectMap.WebApi"
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - main
      - deployment 

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_CORE_VERSION}}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }} --output ${{env.PUBLISH_DIRECTORY}} --configuration Release 
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_DIRECTORY}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_DIRECTORY}}

     # Deploy to Azure Web apps
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: <publishData><publishProfile profileName="${{secrets.AZURE_WEBAPP_NAME}} - Zip Deploy" publishMethod="ZipDeploy" publishUrl="${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443" userName="${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}" userPWD="${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}" destinationAppUrl="http://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
        package: '${{ env.PUBLISH_DIRECTORY}}'